<?php


namespace common\modules\ws\widgets\chat;


use yii\base\Widget;

class Chat extends Widget
{


    public function run()
    {
        parent::run(); // TODO: Change the autogenerated stub
    }
}